# https://jekyllrb.com/docs/configuration/default/
#lsi: false
safe: true
#source: ./_site
#incremental: false
#highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM
  parse_block_html: true
  syntax_highlighter_opts:
    disable: true
baseurl: "/ck-apstra-api"
title: "CK Apstra API Documentation"
markdown: kramdown