# https://jekyllrb.com/docs/configuration/default/
#lsi: false
safe: true
#source: ./_site
#incremental: false
#highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM
  parse_block_html: true
  syntax_highlighter_opts:
    disable: true

title: CK Apstra API
description: Documentation for CK Apstra API
baseurl: "/ck-apstra-api"  # Match your GitHub repository name
url: "https://github.com/kimcharli/ck-apstra-api"  # Your GitHub Pages URL

# Build settings
markdown: kramdown
remote_theme: jekyll/minima

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Include assets directory
include:
  - assets
  - assets/css

# Sass/SCSS processing
sass:
  sass_dir: _sass
  style: compressed

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor